### ISSUE TITLE
bug deploy building

### ISSUE THREAD

**Issue by SlowMo24** [cornernote/minetest-deploy_nodes#1]
Hi,

thanks for this cool mod! I had a bug thou when activating deploy buildings. To debug I simply had to add a \ in line 25:
        os.execute('\ls -a "'..modpath..'/buildings/'..size..'/" | grep .we > "'..modpath..'/buildings/'..size..'/_buildings"') -- linux/mac

I am playing on Ubuntu 14.04
cheers

**Comment by cornernote** [comment]
Hey @SlowMo24,

I checked the code, and it already starts with a `\`
https://github.com/cornernote/minetest-deploy_nodes/blob/master/deploy_building/init.lua#L25

**Comment by SlowMo24** [comment]
Thanks for checking :-) but to make it work for me there had to be two \
        os.execute('\ \ls -a "'..modpath..'/buildings/'..size..'/" | grep .we > "'..modpath..'/buildings/'..size..'/_buildings"') -- linux/mac
(sorry I posted the original one first)
I don't know the reason because I'm not really into lua-coding
EDIT: the second one gets deleted when i submit the post, so i had to place a SPACE between them, that should not be in the code, though
